#!/bin/bash
mkdir -p /var/log/apt-cacher-ng
chown -R apt-cacher-ng:apt-cacher-ng /var/log/apt-cacher-ng

mkdir -p /var/cache/apt-cacher-ng
chown -R apt-cacher-ng:apt-cacher-ng /var/cache/apt-cacher-ng

exec sudo /usr/sbin/apt-cacher-ng \
-c /etc/apt-cacher-ng \
pidfile=/var/run/apt-cacher-ng/pid \
SocketPath=/var/run/apt-cacher-ng/socket \
foreground=1
